
services:
  web:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8000:80"  # Ya lo tenia para jenkins el 8080
    volumes:
      - ./:/usr/share/nginx/html:ro  # Monta todo el contenido de la carpeta Taller en Nginx. Debi ser mas ordenado
    networks:
      - webnet #la red dentro de podman es distinta a la de jenkins

networks:
  webnet:
    driver: bridge  # Bridge es la red por defecto y tiene acceso a Internet
