
services:
  app:
    image: node:14  # Usar una imagen Node.js adecuada
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - app_data:/usr/src/app
    command: bash -c "npm install && npm run start"
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del contenedor al 3000 del host
    networks:
      - webnet

  web:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8000:80"  # Exponer Nginx en el puerto 8000 en la máquina host
    volumes:
      - web_data:/usr/share/nginx/html  # Monta todo el contenido de la carpeta Taller en Nginx
    networks:
      - webnet

networks:
  webnet:

